<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userrpc.proto

namespace User;

if (false) {
    /**
     * This class is deprecated. Use User\UserRequest\Address instead.
     * @deprecated
     */
    class UserRequest_Address {}
}
class_exists(UserRequest\Address::class);
@trigger_error('User\UserRequest_Address is deprecated and will be removed in the next major release. Use User\UserRequest\Address instead', E_USER_DEPRECATED);

