<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userrpc.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request message for creating a new user
 *
 * Generated from protobuf message <code>user.UserRequest</code>
 */
class UserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique ID number for a User.
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>string phone = 4;</code>
     */
    private $phone = '';
    /**
     * Generated from protobuf field <code>repeated .user.UserRequest.Address addresses = 5;</code>
     */
    private $addresses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           Unique ID number for a User.
     *     @type string $name
     *     @type string $email
     *     @type string $phone
     *     @type \User\UserRequest\Address[]|\Google\Protobuf\Internal\RepeatedField $addresses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Userrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique ID number for a User.
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Unique ID number for a User.
     *
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 4;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .user.UserRequest.Address addresses = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .user.UserRequest.Address addresses = 5;</code>
     * @param \User\UserRequest\Address[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \User\UserRequest\Address::class);
        $this->addresses = $arr;

        return $this;
    }

}

