// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userrpc.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for creating a new user
type UserRequest struct {
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*UserRequest_Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_822e9b63a41ff3fd, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserRequest) GetAddresses() []*UserRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type UserRequest_Address struct {
	Province             string   `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest_Address) Reset()         { *m = UserRequest_Address{} }
func (m *UserRequest_Address) String() string { return proto.CompactTextString(m) }
func (*UserRequest_Address) ProtoMessage()    {}
func (*UserRequest_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_822e9b63a41ff3fd, []int{0, 0}
}

func (m *UserRequest_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest_Address.Unmarshal(m, b)
}
func (m *UserRequest_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest_Address.Marshal(b, m, deterministic)
}
func (m *UserRequest_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest_Address.Merge(m, src)
}
func (m *UserRequest_Address) XXX_Size() int {
	return xxx_messageInfo_UserRequest_Address.Size(m)
}
func (m *UserRequest_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest_Address.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest_Address proto.InternalMessageInfo

func (m *UserRequest_Address) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *UserRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

type UserResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_822e9b63a41ff3fd, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserFilter struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFilter) Reset()         { *m = UserFilter{} }
func (m *UserFilter) String() string { return proto.CompactTextString(m) }
func (*UserFilter) ProtoMessage()    {}
func (*UserFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_822e9b63a41ff3fd, []int{2}
}

func (m *UserFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFilter.Unmarshal(m, b)
}
func (m *UserFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFilter.Marshal(b, m, deterministic)
}
func (m *UserFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFilter.Merge(m, src)
}
func (m *UserFilter) XXX_Size() int {
	return xxx_messageInfo_UserFilter.Size(m)
}
func (m *UserFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFilter.DiscardUnknown(m)
}

var xxx_messageInfo_UserFilter proto.InternalMessageInfo

func (m *UserFilter) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*UserRequest_Address)(nil), "user.UserRequest.Address")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*UserFilter)(nil), "user.UserFilter")
}

func init() { proto.RegisterFile("userrpc.proto", fileDescriptor_822e9b63a41ff3fd) }

var fileDescriptor_822e9b63a41ff3fd = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x6c, 0xda, 0xf4, 0xb5, 0xd9, 0xbc, 0x22, 0xb0, 0x38, 0x98, 0x88, 0x43, 0x94, 0x53, 0x4e,
	0x29, 0x6a, 0x85, 0x80, 0x23, 0x20, 0xc1, 0xdd, 0x12, 0x17, 0x6e, 0xc1, 0x59, 0x81, 0xa5, 0x36,
	0x31, 0x5e, 0x07, 0x89, 0xcf, 0xe4, 0x8f, 0x90, 0x6d, 0x4a, 0x2b, 0x72, 0xdb, 0x19, 0xcf, 0xec,
	0xce, 0xc8, 0xb0, 0xe8, 0x09, 0x8d, 0xd1, 0xb2, 0xd2, 0xa6, 0xb3, 0x1d, 0x8b, 0x1d, 0x2c, 0xbe,
	0x22, 0x48, 0x9f, 0x08, 0x8d, 0xc0, 0xf7, 0x1e, 0xc9, 0xb2, 0x23, 0x18, 0xab, 0x86, 0x47, 0x79,
	0x54, 0x4e, 0xc5, 0x58, 0x35, 0x8c, 0x41, 0xdc, 0xd6, 0x5b, 0xe4, 0xe3, 0x3c, 0x2a, 0x13, 0xe1,
	0x67, 0x76, 0x0a, 0x53, 0xdc, 0xd6, 0x6a, 0xc3, 0x27, 0x9e, 0x0c, 0xc0, 0xb1, 0xfa, 0xad, 0x6b,
	0x91, 0xc7, 0x81, 0xf5, 0x80, 0x5d, 0x41, 0x52, 0x37, 0x8d, 0x41, 0x22, 0x24, 0x3e, 0xcd, 0x27,
	0x65, 0xba, 0x3a, 0xab, 0xdc, 0xe5, 0xea, 0xe0, 0x6a, 0x75, 0x1b, 0x24, 0x62, 0xaf, 0xcd, 0x6e,
	0x60, 0xf6, 0xc3, 0xb2, 0x0c, 0xe6, 0xda, 0x74, 0x1f, 0xaa, 0x95, 0xe8, 0x93, 0x25, 0xe2, 0x17,
	0xbb, 0x7c, 0x52, 0xd9, 0xcf, 0x5d, 0x3e, 0x37, 0x17, 0xd7, 0xf0, 0x3f, 0x2c, 0x27, 0xdd, 0xb5,
	0x84, 0x83, 0x4e, 0x1c, 0x66, 0xd4, 0x4b, 0x89, 0x44, 0xde, 0x36, 0x17, 0x3b, 0x58, 0x9c, 0x03,
	0x38, 0xe7, 0x83, 0xda, 0x58, 0x34, 0x7f, 0x7d, 0x2b, 0x03, 0xb1, 0x7b, 0x65, 0x6b, 0x98, 0x3f,
	0xa2, 0x75, 0x23, 0xb1, 0xe3, 0x7d, 0x99, 0xe0, 0xca, 0x4e, 0x06, 0xf5, 0x8a, 0xd1, 0x45, 0xc4,
	0x2e, 0x01, 0xee, 0x0d, 0xd6, 0x16, 0xfd, 0x8a, 0xa1, 0x28, 0x63, 0x87, 0x54, 0x48, 0x5e, 0x8c,
	0xee, 0x16, 0xcf, 0x69, 0xb5, 0x7c, 0x35, 0x5a, 0x2e, 0xdd, 0xeb, 0xcb, 0x3f, 0xff, 0x77, 0xeb,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xe1, 0x49, 0x0e, 0xcc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	// Get all Users with id - A server-to-client streaming RPC.
	GetUsers(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (User_GetUsersClient, error)
	// Create a new User - A simple RPC
	CreateUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUsers(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (User_GetUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_User_serviceDesc.Streams[0], "/user.User/GetUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userGetUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type User_GetUsersClient interface {
	Recv() (*UserRequest, error)
	grpc.ClientStream
}

type userGetUsersClient struct {
	grpc.ClientStream
}

func (x *userGetUsersClient) Recv() (*UserRequest, error) {
	m := new(UserRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.User/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	// Get all Users with id - A server-to-client streaming RPC.
	GetUsers(*UserFilter, User_GetUsersServer) error
	// Create a new User - A simple RPC
	CreateUser(context.Context, *UserRequest) (*UserResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetUsers(req *UserFilter, srv User_GetUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedUserServer) CreateUser(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServer).GetUsers(m, &userGetUsersServer{stream})
}

type User_GetUsersServer interface {
	Send(*UserRequest) error
	grpc.ServerStream
}

type userGetUsersServer struct {
	grpc.ServerStream
}

func (x *userGetUsersServer) Send(m *UserRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUsers",
			Handler:       _User_GetUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "userrpc.proto",
}
